when:
  and:
    - << pipeline.parameters.release >>
jobs:
  - verify_circleci_config
  - install:
      requires:
        - verify_circleci_config
  - lint:
      requires:
        - install
  - tests:
      requires:
        - install
  - release:
      requires:
        - lint
        - tests